name: CustomJoin
main: XGDAVIDYT\Join\Main
version: 1.0.1
api: 3.0.0
author: XGDAVIDYT


 # Please do not remove ANY Code/Modify or Copy!
 # Standard Copyright License applied.
 # All rights reserved XGTeam ©2020
 # www.youtube.com/xgdavid
