---

# Color - §


#	Join Message
#
# {$name} = player name
#
#		|	|	|	|
#		↓	↓	↓	↓
JoinMessage1: "§aHello "
JoinMessage2: "§e Have fun!"


#	Join Effect
#
#	ids	effect
#	↓	↓
#	1	Speed
#	2	Slowness
#	3	Haste
#	4	Mining Fatigue
#	5	Strength
#	6	Instant Health
#	7	Instant Damage
#	8	Jump Boost
#	9	Nausea
#	10	Regeneration
#	11	Resistance
#	12	Fire Resistance
#	13	Water Breathing
#	14	Invisibility
#	15	Blindness
#	16	Night Vision
#	17	Hunger
#	18	Weakness
#	19	Poison
#	20	Wither
#	21	Health Boost
#	22	Absorption
#	23	Saturation
#	24	Glowing
#	25	Levitation
#	26	Luck
#	27	Bad Luck
JoinEffect: 1

#
#	Join Effect Duration
# in seconds
#
#		|	|	|	|
#		↓	↓	↓	↓
Duration: 30

#
# Join Effect Level
#
#		|	|	|	|
#		↓	↓	↓	↓
Level: 1



...
